Repository gdsc-konkuk/24-25-proj-U2E-Client, pull requests merged in 2025-05, with the labels that each got.

#14 #13: 헤더 기후필터, 검색창 UI 및 뉴스 기사 미리보기 컴포넌트 구현
  src/assets/svgs/Warning.svg
  src/assets/svgs/climate/Drought.svg
  src/assets/svgs/climate/Dust.svg
  src/assets/svgs/climate/Rain.svg
  src/assets/svgs/climate/SeaLevel.svg
  src/assets/svgs/climate/Temperature.svg
  src/assets/svgs/climate/Tornado.svg
  src/assets/svgs/search.svg
  src/components/common/Layout.tsx
  src/components/common/header/FilterBar.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/SearchBox.tsx
  src/components/earth/Earth.tsx
  src/components/earth/Warning.tsx
  src/pages/Main.tsx
Labels: feat

#17 #16: msw 라이브러리 추가
  .gitignore
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/components/chat/Comments.tsx
  src/hooks/dummy.txt
  src/hooks/useApi.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
  src/vite-env.d.ts
  tsconfig.app.json
Labels: feat

#21 #20: 댓글창 UI 및 기능 구현
  src/api/commentApi.ts
  src/assets/svgs/SendIcon.svg
  src/assets/svgs/UserIcon.svg
  src/components/chat/ChatPanel.tsx
  src/components/chat/CommentCard.tsx
  src/components/chat/Comments.tsx
  src/components/chat/UserInput.tsx
  src/components/news/NewsCard.tsx
  src/hooks/useCommentsQuery.ts
  src/mocks/handlers.ts
  src/styles/globalStyles.ts
  src/types/dummy.txt
  src/types/request.d.ts
  src/types/response.d.ts
Labels: feat

#23 #22: 비 애니메이션 구현 및 적용
  src/components/animation/DetailAnimation.tsx
  src/components/earth/Warning.tsx
  src/pages/NewsDetail.tsx
Labels: feat

#25 #24: 뉴스, 댓글 조회 기능 API 연결
  src/api/commentApi.ts
  src/api/newsApi.ts
  src/components/chat/CommentCard.tsx
  src/components/news/NewsCard.tsx
  src/components/news/NewsCardList.tsx
  src/components/news/NewsContents.tsx
  src/hooks/useNewsQuery.ts
  src/pages/Main.tsx
  src/pages/NewsDetail.tsx
  src/types/news.d.ts
  src/types/response.d.ts
Labels: feat

#26 #15: 3D 지구본 컴포넌트 구현, 특정 좌표에 핀 찍기
  .gitignore
  land.json
  package.json
  pnpm-lock.yaml
  src/components/earth/Earth.tsx
  src/components/earth/GeoMap.tsx
  src/components/earth/GeoPolygonFill.ts
  src/components/earth/Globe.tsx
  src/components/earth/Starfield.tsx
  src/components/earth/Warning.tsx
  src/components/earth/threeGEO.ts
  src/pages/Main.tsx
  src/types/geo.d.ts
  src/types/response.d.ts
  src/utils/dummy.txt
  src/utils/geoUtils.ts
Labels: feat

#28 #24: 댓글 작성 API 연동 및 기타 리팩토링
  src/api/client.ts
  src/api/commentApi.ts
  src/api/loginApi.ts
  src/api/newsApi.ts
  src/components/chat/CommentCard.tsx
  src/components/chat/Login.tsx
  src/components/chat/UserInput.tsx
  src/components/earth/GeoMap.tsx
  src/components/news/NewsCard.tsx
  src/components/news/NewsCardList.tsx
  src/hooks/useCommentsQuery.ts
  src/hooks/useLoginQuery.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/Main.tsx
  src/types/login.d.ts
  src/types/request.d.ts
  src/types/response.d.ts
Labels: enhancement, feat

#29 land.json 파일 경로 변경
  public/land.json
Labels: build

#30 #27: 핀 API 연동
  public/land.json
  src/api/commentApi.ts
  src/api/newsApi.ts
  src/api/pinApi.ts
  src/components/common/header/FilterBar.tsx
  src/components/earth/Earth.tsx
  src/components/earth/Globe.tsx
  src/components/earth/Warning.tsx
  src/constants/climateIcons.ts
  src/hooks/usePinsQuery.ts
  src/types/pin.d.ts
  src/types/response.d.ts
Labels: feat

#34 #33: Gemini API를 이용한 솔루션 제공 및 관련 뉴스 기사 가져오기
  package.json
  pnpm-lock.yaml
  src/api/geminiApi.ts
  src/components/news/NewsContents.tsx
  src/components/news/NewsSideBar.tsx
  src/types/response.d.ts
  src/vite-env.d.ts
Labels: feat
